name: Java CI/CD vli

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK18
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 18
      - name: Unit test
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Build Docker image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-cicd:latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Додаткові кроки для запуску Docker контейнера можуть бути реалізовані тут
